# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f15e9aacf85bdb453cac4b2d280dd9aa4b0750394e52710a8e1c18711e6b292bc408981851c80d829475bd76961fa893bdb92eb0a49fdfb60dd44346aa1d2de8

test:
  secret_key_base: 0ab871edb84af7f304a6251a5e87fa6a1c9508b4dbb51afb59213a9f8b95cb71184a0a467094b318fe53a34cc0bab3d975dcf2e9467b95a519df897106712805

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
